// This file is automatically generated. Do not modify it manually.

package plugin

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "mattermost-plugin-servicenow",
	Version: "2.2.0",
}
